export enum FormEnum {
    // HR Forms
    EMPLOYEE_LIST = 'EMPLOYEE_LIST',
    EMPLOYEE_CREATE = 'EMPLOYEE_CREATE',
    EMPLOYEE_EDIT = 'EMPLOYEE_EDIT',

    // Inventory Forms
    PRODUCT_LIST = 'PRODUCT_LIST',
    PRODUCT_CREATE = 'PRODUCT_CREATE',
    PRODUCT_EDIT = 'PRODUCT_EDIT',
    STOCK_ADJUST = 'STOCK_ADJUST',

    // Sales Forms
    POS_SALE = 'POS_SALE',
    SALE_RETURN = 'SALE_RETURN',

    // Settings Forms
    DESIGNATION_MANAGE = 'DESIGNATION_MANAGE',
    PERMISSION_MANAGE = 'PERMISSION_MANAGE',
}